/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ClienteController;
import Model.ClienteModel;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno(a) TDS Noite
 */
public class GestaoLivro extends javax.swing.JFrame {

    /**
     * Creates new form RetiradaLivro
     */
    public GestaoLivro() {
        initComponents();
        ListarClientesView();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblRetirada = new javax.swing.JLabel();
        panelTabelaLivro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLivro = new javax.swing.JTable();
        panelTabelaCliente = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        panelFiltroLivro = new javax.swing.JPanel();
        lblIDLivro = new javax.swing.JLabel();
        txtIDLivro = new javax.swing.JTextField();
        btnFiltrarLivro = new javax.swing.JButton();
        panelFiltroCliente = new javax.swing.JPanel();
        lblIDCliente = new javax.swing.JLabel();
        txtIDCliente = new javax.swing.JTextField();
        btnFiltrarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 800));

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblRetirada.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRetirada.setText("Gestão de Livros");

        panelTabelaLivro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela Livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        tableLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableLivro);

        javax.swing.GroupLayout panelTabelaLivroLayout = new javax.swing.GroupLayout(panelTabelaLivro);
        panelTabelaLivro.setLayout(panelTabelaLivroLayout);
        panelTabelaLivroLayout.setHorizontalGroup(
            panelTabelaLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelTabelaLivroLayout.setVerticalGroup(
            panelTabelaLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaLivroLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTabelaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Permissão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCliente);

        javax.swing.GroupLayout panelTabelaClienteLayout = new javax.swing.GroupLayout(panelTabelaCliente);
        panelTabelaCliente.setLayout(panelTabelaClienteLayout);
        panelTabelaClienteLayout.setHorizontalGroup(
            panelTabelaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelTabelaClienteLayout.setVerticalGroup(
            panelTabelaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaClienteLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelFiltroLivro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtro Livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        lblIDLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIDLivro.setText("ID:");

        txtIDLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnFiltrarLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFiltrarLivro.setText("Filtrar");
        btnFiltrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFiltroLivroLayout = new javax.swing.GroupLayout(panelFiltroLivro);
        panelFiltroLivro.setLayout(panelFiltroLivroLayout);
        panelFiltroLivroLayout.setHorizontalGroup(
            panelFiltroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIDLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFiltrarLivro)
                .addContainerGap())
        );
        panelFiltroLivroLayout.setVerticalGroup(
            panelFiltroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroLivroLayout.createSequentialGroup()
                .addGroup(panelFiltroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIDLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIDLivro))
                    .addComponent(btnFiltrarLivro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFiltroCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtro Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        panelFiltroCliente.setPreferredSize(new java.awt.Dimension(10, 132));

        lblIDCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIDCliente.setText("ID:");

        txtIDCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnFiltrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFiltrarCliente.setText("Filtrar");
        btnFiltrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFiltroClienteLayout = new javax.swing.GroupLayout(panelFiltroCliente);
        panelFiltroCliente.setLayout(panelFiltroClienteLayout);
        panelFiltroClienteLayout.setHorizontalGroup(
            panelFiltroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIDCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFiltrarCliente)
                .addContainerGap())
        );
        panelFiltroClienteLayout.setVerticalGroup(
            panelFiltroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroClienteLayout.createSequentialGroup()
                .addGroup(panelFiltroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDCliente)
                    .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrarCliente))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVoltar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(lblRetirada)))
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTabelaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTabelaLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelFiltroLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelFiltroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRetirada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFiltroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTabelaLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFiltroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTabelaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnFiltrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarLivroActionPerformed
         int itemPesquisa = Integer.parseInt(txtIDCliente.getText());
        try {
            DefaultTableModel dtm = (DefaultTableModel) tableCliente.getModel();
            dtm.setRowCount(0);
            ClienteController clienteController = new ClienteController();
            
            ArrayList<ClienteModel> listaCliente = clienteController.searchClient(itemPesquisa);
            Iterator<ClienteModel> iteratorCliente = listaCliente.iterator();
            while (iteratorCliente.hasNext()) {
                ClienteModel cliente = iteratorCliente.next();
                dtm.addRow(new Object[]{
                    cliente.getId(),
                    cliente.getNome(),
                    cliente.isStatus()
                });
                JOptionPane.showMessageDialog(null, "funcionando no view");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "deu merda");
        }
    }//GEN-LAST:event_btnFiltrarLivroActionPerformed

    private void btnFiltrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarClienteActionPerformed
        int itemPesquisa = Integer.parseInt(txtIDCliente.getText());
        try {
            DefaultTableModel dtm = (DefaultTableModel) tableCliente.getModel();
            dtm.setRowCount(0);
            ClienteController clienteController = new ClienteController();
            ArrayList<ClienteModel> listaClientes = clienteController.searchClient(itemPesquisa);
            
            Iterator<ClienteModel> iteratorCliente = listaClientes.iterator();
            while (iteratorCliente.hasNext()) {
                ClienteModel cliente = iteratorCliente.next();
                dtm.addRow(new Object[]{
                    cliente.getId(),
                    cliente.getNome(),
                    cliente.isStatus()
                });
                JOptionPane.showMessageDialog(null, "funcionando no view");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "deu merda"+e);
        }
    }//GEN-LAST:event_btnFiltrarClienteActionPerformed

     void ListarClientesView() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tableCliente.getModel();
            dtm.setRowCount(0);
            ClienteController clienteController = new ClienteController();

            ArrayList<ClienteModel> listaCliente = clienteController.listarClientesController();

            Iterator<ClienteModel> iterator = listaCliente.iterator();
            while (iterator.hasNext()) {
                ClienteModel cliente = iterator.next();
                dtm.addRow(new Object[]{
                    cliente.getId(),
                    cliente.getNome(),
                    cliente.isStatus()
                });
                        
            }

        } catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestaoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestaoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestaoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestaoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestaoLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrarCliente;
    private javax.swing.JButton btnFiltrarLivro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIDCliente;
    private javax.swing.JLabel lblIDLivro;
    private javax.swing.JLabel lblRetirada;
    private javax.swing.JPanel panelFiltroCliente;
    private javax.swing.JPanel panelFiltroLivro;
    private javax.swing.JPanel panelTabelaCliente;
    private javax.swing.JPanel panelTabelaLivro;
    private javax.swing.JTable tableCliente;
    private javax.swing.JTable tableLivro;
    private javax.swing.JTextField txtIDCliente;
    private javax.swing.JTextField txtIDLivro;
    // End of variables declaration//GEN-END:variables
}
