/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Aluno(a) TDS Noite
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form CRUDAutor
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloCima = new javax.swing.JLabel();
        btnCadastroAutor = new javax.swing.JButton();
        btnCadastroLivro = new javax.swing.JButton();
        btnCadastroCliente = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblTituloBaixo = new javax.swing.JLabel();
        btnRetiradaLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 800));
        setSize(new java.awt.Dimension(600, 800));

        lblTituloCima.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTituloCima.setText("Biblioteca Municipal");

        btnCadastroAutor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastroAutor.setText("Cadastro Autor");
        btnCadastroAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroAutorActionPerformed(evt);
            }
        });

        btnCadastroLivro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastroLivro.setText("Cadastro Livro");
        btnCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroLivroActionPerformed(evt);
            }
        });

        btnCadastroCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastroCliente.setText("Cadastro Cliente");
        btnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClienteActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblTituloBaixo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTituloBaixo.setText("de São Leopoldo");

        btnRetiradaLivro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRetiradaLivro.setText("Retirada de Livro");
        btnRetiradaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiradaLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair)
                .addContainerGap(522, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTituloCima)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnCadastroLivro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCadastroAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRetiradaLivro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTituloBaixo))
                        .addGap(154, 154, 154))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloCima)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloBaixo)
                .addGap(28, 28, 28)
                .addComponent(btnCadastroAutor)
                .addGap(18, 18, 18)
                .addComponent(btnCadastroLivro)
                .addGap(18, 18, 18)
                .addComponent(btnCadastroCliente)
                .addGap(18, 18, 18)
                .addComponent(btnRetiradaLivro)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastroAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroAutorActionPerformed
        
        CRUDAutor autor = new CRUDAutor();
        
        autor.setVisible(true);
    }//GEN-LAST:event_btnCadastroAutorActionPerformed

    private void btnCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroLivroActionPerformed
        
        CRUDLivro livro = new CRUDLivro();
        
        livro.setVisible(true);
    }//GEN-LAST:event_btnCadastroLivroActionPerformed

    private void btnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClienteActionPerformed
        
        CRUDCliente cliente = new CRUDCliente();
        
        cliente.setVisible(true);
    }//GEN-LAST:event_btnCadastroClienteActionPerformed

    private void btnRetiradaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiradaLivroActionPerformed
        
        RetiradaLivro retirarLivro = new RetiradaLivro();
        
        retirarLivro.setVisible(true);
    }//GEN-LAST:event_btnRetiradaLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroAutor;
    private javax.swing.JButton btnCadastroCliente;
    private javax.swing.JButton btnCadastroLivro;
    private javax.swing.JButton btnRetiradaLivro;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblTituloBaixo;
    private javax.swing.JLabel lblTituloCima;
    // End of variables declaration//GEN-END:variables
}
